
extend( W, {
        bind: bind,
        call: call,
        clone: clone,
        compose: compose,
        composeAsync: composeAsync,
        composePromisers: composePromisers,
        countedCallbackMixin: countedCallbackMixin,
        cycle: cycle,
        each: each,
        eventMixin: eventMixin,
        extend: extend,
        first: first,
        flatten: flatten,
        flip: flip,
        interpose: interpose,
        isDefined: isDefined,
        isNotOk: isNotOk,
        isNotUndefined : isNotUndefined,
        isOk: isOk,
        isUndefined: isUndefined,
        last: last,
        list: list,
        loop: loop,
        Middleware: Middleware,
        Object: Obj,
        partial: partial,
        partialRight: partialRight,
        partition: partition,
        promise: promise,
        promiseWrap: promiseWrap,
        range: range,
        rest: rest,
        Router: Router,
        Sequence: Sequence,
        sequence: sequence,
        take: take,
        TickTimer: TickTimer,
        Timer: Timer,
        toArray: toArray,
        toPartition: toPartition,
        withoutLast: withoutLast
    });
} ( W ) );
