	W.interpolations = {
		backEaseIn: backEaseIn, 
		backEaseInOut: backEaseInOut, 
		backEaseOut: backEaseOut, 
		bounceEaseIn: bounceEaseIn, 
		bounceEaseInOut: bounceEaseInOut,
		bounceEaseOut: bounceEaseOut, 
		circularEaseIn: circularEaseIn, 
		circularEaseInOut: circularEaseInOut, 
		circularEaseOut: circularEaseOut, 
		cubicEaseIn: cubicEaseIn, 
		cubicEaseInOut: cubicEaseInOut, 
		cubicEaseOut: cubicEaseOut, 
		elasticEaseIn: elasticEaseIn, 
		elasticEaseInOut: elasticEaseInOut, 
		elasticEaseOut: elasticEaseOut, 
		exponentialEaseIn: exponentialEaseIn, 
		exponentialEaseInOut: exponentialEaseInOut, 
		exponentialEaseOut: exponentialEaseOut, 
		linearInterpolation: linearInterpolation,
		quadraticEaseIn: quadraticEaseIn, 
		quadraticEaseInOut: quadraticEaseInOut, 
		quadraticEaseOut: quadraticEaseOut, 
		quarticEaseIn: quarticEaseIn, 
		quarticEaseInOut: quarticEaseInOut, 
		quarticEaseOut: quarticEaseOut, 
		quinticEaseIn: quinticEaseIn, 
		quinticEaseInOut: quinticEaseInOut, 
		quinticEaseOut: quinticEaseOut, 
		sineEaseIn: sineEaseIn, 
		sineEaseInOut: sineEaseInOut, 
		sineEaseOut: sineEaseOut
	};

} ( W ) );
